# Generated by Django 3.1.7 on 2021-02-21 07:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_user_staff'),
    ]

    operations = [
        migrations.RenameField(
            model_name='phoneotp',
            old_name='otp',
            new_name='code',
        ),
    ]
