# Generated by Django 3.1.7 on 2021-02-21 16:04

import accounts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20210221_0700'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='image',
            field=models.ImageField(blank=True, default=None, null=True, upload_to=accounts.models.upload_image_path_profile),
        ),
    ]
