# Generated by Django 3.1.7 on 2021-03-22 11:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_auto_20210221_1606'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='phoneotp',
            options={'verbose_name': 'Confirmation code', 'verbose_name_plural': 'Confirmation codes'},
        ),
    ]
